### ISSUE TITLE
Meet with UX Experts from Other Agile Teams (from DevExchange)

### ISSUE THREAD

**Issue by MariaChenBCGov** [allanhaggett/learning-curator#169]
Some UX people recommend "engaging the UX community." Shall we take 'em up on it? ;)

**Comment by MariaChenBCGov** [comment]
- [ ] reach out to 2 UX experts at DevExchange

**Comment by shannonator** [comment]
Emailed Heather Remacle Oct. 20th.

**Comment by MariaChenBCGov** [comment]
Maria to reach out to Inderdeep & another experienced UX designer (name to update)

**Comment by cohiggins** [comment]
NFS: #169
We determined it wasn’t time to meet up with the UX experts until we were settled on the new server and had direction from CLDF – since that could significantly change the landing area of the product and give us direction for how they wanted to serve the employees via the curator. Now that CLDF is delayed once again and we’ve started to use the tool for our own purposes in the Learning Centre, that’s less of an issue I think… Let’s kill this ticket and return to the idea once the back end functionality is set.
