### ISSUE TITLE
Get Access to BC Gov OCP4

### ISSUE THREAD

**Issue by fuxingli** [allanhaggett/learning-curator#224]
The project name space for Learning Curation is setup already and Allan has the access to it.
Allan and Kousthubha will join one of the live session to see how to get the same access for Kousthubha and Warren.
Help from David might be required.

**Comment by allanhaggett** [comment]
David & I went through the process a minute ago and filed the following ticket:

[https://github.com/BCDevOps/devops-requests/issues/672](https://github.com/BCDevOps/devops-requests/issues/672)

They acted on it almost immediately (closed), and Kousthubha should now have access to the namespace in the console.

@Kousthubha-M I will leave it to you to comment from here if you do indeed have access. I'm not sure if I should paste the link to console dashboard here; can provide you with the link privately.

**Comment by allanhaggett** [comment]
We would have to have David file another ticket to get Warren's access ...

**Comment by Kousthubha-M** [comment]
Hey Allan,

I am into BC DevOps successfully. Thanks

**Comment by allanhaggett** [comment]
As noted above, @Kousthubha-M has access to the console, but he cannot see the tools,test,dev,prod namespaces to deploy to. I've sent David an email with the particulars and a link to the above issue so that we may follow up with DevExchange to see what we need to do to make it so K can see what I see.
